# Generated by Django 3.2.9 on 2021-11-20 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('dob', models.IntegerField(blank=True, null=True)),
                ('doe', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pages', models.IntegerField()),
                ('genre', models.CharField(choices=[('ch', 'Charitra'), ('sci', 'science'), ('hea', 'health'), ('nov', 'novel'), ('sto', 'stories')], default='Novel', max_length=3)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('published', models.IntegerField()),
                ('In_stock', models.BooleanField(default=True)),
                ('Wished_by', models.IntegerField(default=0)),
                ('read_by', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.authors')),
            ],
        ),
    ]
