# Generated by Django 3.2.9 on 2021-11-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_passbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
