# Generated by Django 3.2.9 on 2021-11-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20211122_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='passbook',
            name='log_id',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
    ]
