# Generated by Django 3.2.9 on 2021-11-23 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_passbook_log_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passbook',
            name='log_id',
        ),
    ]
