# Generated by Django 3.2.9 on 2021-11-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_passbook_log_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='In_stock',
            new_name='in_stock',
        ),
    ]
