# Generated by Django 3.2.9 on 2021-11-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_in_stock_book_in_stock'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name', 'detail'], name='books_autho_name_5716fe_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['name', 'tags', 'genre'], name='books_book_name_6eccb9_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['name'], name='books_publi_name_fccace_idx'),
        ),
    ]
