# Generated by Django 3.2.9 on 2021-11-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20211120_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
