# Generated by Django 3.2.9 on 2021-11-21 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211121_1140'),
        ('members', '0003_myuser_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='member_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Borrowed_Book', to='books.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(to='books.Book')),
            ],
        ),
    ]
